---
title: "AE Explorer"
author: "gsm.safety Example"
description: "Interactive AE Explorer report rendered from mapped GSM safety data."
index: 1
date: "`r format(Sys.time(), '%B %d, %Y %H:%M:%S %Z')`"
output: html_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```

This example renders the interactive AE Explorer report artifact from a small
mapped subject/adverse-event data set. The same renderer is called by the
`inst/workflow/3_reports/ae_explorer.yaml` workflow.

```{r}
lSpec <- list(
  Mapped_SUBJ = list(subjid = list(type = "character")),
  Mapped_AE = list(
    subjid = list(type = "character"),
    mdrpt_nsv = list(type = "character"),
    mdrsoc_nsv = list(type = "character")
  )
)

lData <- gsm.safety::MakeAeExplorerExampleData()
lSettings <- gsm.safety::MakeAeExplorerSettings(lSpec)
lManifest <- gsm.safety::MakeAeExplorerManifest(
  lData = lData,
  lSettings = lSettings,
  lMeta = list(Type = "Report", ID = "ae_explorer", Output = "html")
)

lReport <- gsm.safety::Report_AE_Explorer(
  lData = lData,
  lSettings = lSettings,
  lManifest = lManifest,
  strOutputDir = tempdir(),
  strOutputFile = "ae_explorer_example"
)

lReport$path
```

```{r, echo = FALSE}
lReport$widget
```
